In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
A = torch.tensor([
    [2, 1, 5],
    [1, 2, 1],
    [2, 1, 3]
], dtype=torch.float)

In [5]:
A.shape

torch.Size([3, 3])

### Determinant

In [6]:
det = torch.linalg.det(A)

In [7]:
det

tensor(-6.0000)

### Solver

In [8]:
b = torch.tensor([20, 10, 15], dtype=torch.float)

In [9]:
b.shape

torch.Size([3])

In [10]:
x = torch.linalg.solve(A, b)

In [11]:
x

tensor([2.5000, 2.5000, 2.5000])

### Rank

In [12]:
rank = torch.linalg.matrix_rank(A)

In [13]:
rank

tensor(3)

### Vector Operations

In [14]:
u = torch.tensor([1, 3])

In [15]:
v = torch.tensor([6, 2])

In [18]:
vec_sum = u + v

In [19]:
vec_sum

tensor([7, 5])

In [20]:
vec_diff = u - v

In [21]:
vec_diff

tensor([-5,  1])

In [22]:
a = torch.tensor([-1, 5, 2])

In [23]:
b = torch.tensor([-3, 6, -4])

In [24]:
dot_product = torch.dot(a, b)

In [25]:
dot_product

tensor(25)

In [28]:
vec_norm = torch.linalg.vector_norm(a.float())

In [30]:
vec_norm

tensor(5.4772)

### Matrix Inverse

In [43]:
A = torch.tensor([
    [5, 2],
    [1, 2]
], dtype=torch.float)

In [44]:
A_inv = torch.linalg.inv(A)

In [45]:
A_inv

tensor([[ 0.2500, -0.2500],
        [-0.1250,  0.6250]])

In [46]:
A @ A_inv

tensor([[1., 0.],
        [0., 1.]])

### Distance

In [47]:
v = torch.tensor([1, 0, 7])

In [48]:
w = torch.tensor([0, -1, 2])

In [49]:
pairwise_distance = torch.nn.PairwiseDistance(p=2)

In [50]:
distance = pairwise_distance(v, w)

In [51]:
distance

tensor(5.1962)

### L2 Norm or Magnitude

In [53]:
p = torch.tensor([1, 0, -3])

In [54]:
q = torch.tensor([-1, 0, -3])

In [56]:
torch.linalg.vector_norm(p.float() - q.float())

tensor(2.)